[package]
name = "eng_fmt"
version = "0.1.0"
edition = "2021"
description = "Zero-depedency rate containing trait providing engineerig notation formatting for f64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
